version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: iam-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitflow_iam_db
      POSTGRES_USER: fitflow_iam_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database/postgres/1_users.sql:/docker-entrypoint-initdb.d/1_users.sql
      - ./database/postgres/2_roles.sql:/docker-entrypoint-initdb.d/2_roles.sql
      - ./database/postgres/3_auth_providers.sql:/docker-entrypoint-initdb.d/3_auth_providers.sql
      - ./database/postgres/4_user_auth.sql:/docker-entrypoint-initdb.d/4_user_auth.sql

volumes:
  postgres_data:
